export const PERMISSIONS_CONSTANT = {
    Pages_Users: "Pages.Users",
    Pages_Tenants: "Pages.Tenants",
    Pages_Roles: "Pages.Roles",
    Admin_WorkFlow: "Admin.Workflow",
    Pages_Home: "Pages.Home",
    Pages_Home_DashBoard_GetCashFlowDashBoard: "Pages.Home.DashBoard.GetCashFlowDashBoard",
    Pages_Home_DashBoard_GetStatusDashBoard: "Pages.Home.DashBoard.GetStatusDashBoard",
    Pages_Home_DashBoard_PercentEntryType: "Pages.Home.DashBoard.PercentEntryType",
    Admin_TransitionPermission: "true",
    Admin_TransitionPermission_Create: "Admin.TransitionPermission.Create",
    Admin_TransitionPermission_Delete: "Admin.TransitionPermission.Delete",
    Admin_TransitionPermission_ViewAll: "Admin.TransitionPermission.ViewAll",

    // workflow
    Admin_Workflow_Create: "Admin.Workflow.Create",
    Admin_Workflow_Delete: "Admin.Workflow.Delete",
    Admin_Workflow_Edit: "Admin.Workflow.Edit",
    Admin_Workflow_ViewAll: "Admin.Workflow.ViewAll",
    Admin_Workflow_ViewDetail: "Admin.Workflow.ViewDetail",
    Admin_WorkflowStatus: "Admin.WorkflowStatus",
    Admin_WorkflowStatus_Create: "Admin.WorkflowStatus.Create",
    Admin_WorkflowStatus_Delete: "Admin.WorkflowStatus.Delete",
    Admin_WorkflowStatus_Edit: "Admin.WorkflowStatus.Edit",
    Admin_WorkflowStatus_ViewAll: "Admin.WorkflowStatus.ViewAll",
    Admin_WorkflowStatus_ViewDetail: "Admin.WorkflowStatus.ViewDetail",
    Admin_WorkflowStatusTransition: "Admin.WorkflowStatusTransition",
    Admin_WorkflowStatusTransition_Create: "Admin.WorkflowStatusTransition.Create",
    Admin_WorkflowStatusTransition_Delete: "Admin.WorkflowStatusTransition.Delete",
    Admin_WorkflowStatusTransition_Edit: "Admin.WorkflowStatusTransition.Edit",
    Admin_WorkflowStatusTransition_ViewAll: "Admin.WorkflowStatusTransition.ViewAll",
    Admin_WorkflowStatusTransition_ViewDetail: "Admin.WorkflowStatusTransition.ViewDetail",

    Directory: "Directory",
    Directory_Currency: "Directory.Currency",
    Directory_Currency_Create: "Directory.Currency.Create",
    Directory_Currency_Delete: "Directory.Currency.Delete",
    Directory_Currency_Edit: "Directory.Currency.Edit",
    Directory_Currency_ViewAll: "Directory.Currency.ViewAll",
    Directory_Currency_ViewDetail: "Directory.Currency.ViewDetail",
    Directory_Bank: "Directory.Bank",
    Directory_Bank_Create: "Directory.Bank.Create",
    Directory_Bank_Edit: "Directory.Bank.Edit",
    Directory_Bank_Delete: "Directory.Bank.Delete",
    Directory_Bank_ViewAll: "Directory.Bank.ViewAll",
    Directory_Bank_ViewDetail: "Directory.Bank.ViewDetail",
    Directory_Account: "Directory.Account",
    Directory_Account_Create: "Directory.Account.Create",
    Directory_Account_Edit: "Directory.Account.Edit",
    Directory_Account_Delete: "Directory.Account.Delete",
    Directory_Account_ViewAll: "Directory.Account.ViewAll",
    Directory_Account_ViewDetail: "Directory.Account.ViewDetail",
    Directory_Branch: "Directory.Branch",
    Directory_Branch_Create: "Directory.Branch.Create",
    Directory_Branch_Edit: "Directory.Branch.Edit",
    Directory_Branch_Delete: "Directory.Branch.Delete",
    Directory_Branch_ViewAll: "Directory.Branch.ViewAll",
    Directory_Branch_ViewDetail: "Directory.Branch.ViewDetail",
    Directory_AccountType: "Directory.AccountType",
    Directory_AccountType_Create: "Directory.AccountType.Create",
    Directory_AccountType_Delete: "Directory.AccountType.Delete",
    Directory_AccountType_Edit: "Directory.AccountType.Edit",
    Directory_AccountType_ViewAll: "Directory.AccountType.ViewAll",
    Directory_AccountType_ViewDetail: "Directory.AccountType.ViewDetail",
    Directory_BankAccount_ViewDetail: " .BankAccount.ViewDetail",

    // finance comment
    Finance_OutcomingEntry_CreateCommentByPost: "Finance.OutcomingEntry.CreateCommentByPost",
    Finance_OutcomingEntry_DeleteComment: "Finance.OutcomingEntry.DeleteComment",
    Finance_OutcomingEntry_GetAllCommentByPost: "Finance.OutcomingEntry.GetAllCommentByPost",
    Finance_OutcomingEntry_UpdateCommentByPost: "Finance.OutcomingEntry.UpdateCommentByPost",

    // 
    Finance_OutcomingEntry_GetTotalValueOutcomingEntry: "Finance.OutcomingEntry.GetTotalValueOutcomingEntry",
    Finance_OutcomingEntry_CEOTransfer: "Finance.OutcomingEntry.CEOTransfer",
    Finance_OutcomingEntry_TransferToEnd: "Finance.OutcomingEntry.TransferToEnd",

    Finance_OutcomingEntry_RemindCEO: "Finance.OutcomingEntry.RemindCEO",
    Finance_OutcomingEntry_RemindCFO: "Finance.OutcomingEntry.RemindCFO",
    // Account
    Account_Directory: "Account.Directory",
    Account_Directory_Account: "Account.Directory.Account",
    Account_Directory_Account_Create: "Account.Directory.Account.Create",
    Account_Directory_Account_Delete: "Account.Directory.Account.Delete",
    Account_Directory_Account_Edit: "Account.Directory.Account.Edit",
    Account_Directory_Account_ViewAll: "Account.Directory.Account.ViewAll",
    Account_Directory_Account_ViewDetail: "Account.Directory.Account.ViewDetail",
    Account_Directory_BankAccount: "Account.Directory.BankAccount",
    Account_Directory_BankAccount_Create: "Account.Directory.BankAccount.Create",
    Account_Directory_BankAccount_Delete: "Account.Directory.BankAccount.Delete",
    Account_Directory_BankAccount_Edit: "Account.Directory.BankAccount.Edit",
    Account_Directory_BankAccount_ViewAll: "Account.Directory.BankAccount.ViewAll",
    Account_Directory_BankAccount_ViewDetail: "Account.Directory.BankAccount.ViewDetail",

    //
    Directory_IncomingEntryType: "Directory.IncomingEntryType",
    Directory_IncomingEntryType_Create: "Directory.IncomingEntryType.Create",
    Directory_IncomingEntryType_Delete: "Directory.IncomingEntryType.Delete",
    Directory_IncomingEntryType_Edit: "Directory.IncomingEntryType.Edit",
    Directory_IncomingEntryType_ViewAll: "Directory.IncomingEntryType.ViewAll",
    Directory_IncomingEntryType_ViewDetail:
        "Directory.IncomingEntryType.ViewDetail",


    Directory_OutcomingEntryType: "Directory.OutcomingEntryType",
    Directory_OutcomingEntryType_Create: "Directory.OutcomingEntryType.Create",
    Directory_OutcomingEntryType_Delete: "Directory.OutcomingEntryType.Delete",
    Directory_OutcomingEntryType_Edit: "Directory.OutcomingEntryType.Edit",
    Directory_OutcomingEntryType_ViewAll: "Directory.OutcomingEntryType.ViewAll",
    Directory_OutcomingEntryType_ViewDetail: "Directory.OutcomingEntryType.ViewDetail",


    Finance: "Finance",
    // bank transaction

    Finance_BankTransaction: "Finance.BankTransaction",
    Finance_BankTransaction_Create: "Finance.BankTransaction.Create",
    Finance_BankTransaction_Delete: "Finance.BankTransaction.Delete",
    Finance_BankTransaction_Edit: "Finance.BankTransaction.Edit",
    Finance_BankTransaction_GetAllOutcomingEntryByTransaction: "Finance.BankTransaction.GetAllOutcomingEntryByTransaction",
    Finance_BankTransaction_ViewAll: "Finance.BankTransaction.ViewAll",
    Finance_BankTransaction_ViewDetail: "Finance.BankTransaction.ViewDetail",
    // revenue record

    Finance_IncomingEntry: "Finance.IncomingEntry",
    Finance_IncomingEntry_Create: "Finance.IncomingEntry.Create",
    Finance_IncomingEntry_Delete: "Finance.IncomingEntry.Delete",
    Finance_IncomingEntry_Edit: "Finance.IncomingEntry.Edit",
    Finance_IncomingEntry_ViewAll: "Finance.IncomingEntry.ViewAll",
    Finance_IncomingEntry_ViewAllByBankTransaction: "Finance.IncomingEntry.ViewAllByBankTransaction",
    Finance_IncomingEntry_ViewDetail: "Finance.IncomingEntry.ViewDetail",

    // expenditure request

    Finance_OutcomingEntry: "Finance.OutcomingEntry",
    Finance_OutcomingEntry_ChangeStatus: "Finance.OutcomingEntry.ChangeStatus",
    Finance_OutcomingEntry_Create: "Finance.OutcomingEntry.Create",
    Finance_OutcomingEntry_Delete: "Finance.OutcomingEntry.Delete",
    Finance_OutcomingEntry_Edit: "Finance.OutcomingEntry.Edit",
    Finance_OutcomingEntry_OutcomingEntryDetail: "Finance.OutcomingEntry.OutcomingEntryDetail",
    Finance_OutcomingEntry_OutcomingEntryDetail_AddMultipleTransactions: "Finance.OutcomingEntry.OutcomingEntryDetail.AddMultipleTransactions",
    Finance_OutcomingEntry_OutcomingEntryDetail_AddTransaction: "Finance.OutcomingEntry.OutcomingEntryDetail.AddTransaction",
    Finance_OutcomingEntry_OutcomingEntryDetail_Create: "Finance.OutcomingEntry.OutcomingEntryDetail.Create",
    Finance_OutcomingEntry_OutcomingEntryDetail_Delete: "Finance.OutcomingEntry.OutcomingEntryDetail.Delete",
    Finance_OutcomingEntry_OutcomingEntryDetail_DeleteLinkedTransaction: "Finance.OutcomingEntry.OutcomingEntryDetail.DeleteLinkedTransaction",
    Finance_OutcomingEntry_OutcomingEntryDetail_Edit: "Finance.OutcomingEntry.OutcomingEntryDetail.Edit",
    Finance_OutcomingEntry_OutcomingEntryDetail_GetTransactionDetails: "Finance.OutcomingEntry.OutcomingEntryDetail.GetTransactionDetails",
    Finance_OutcomingEntry_OutcomingEntryDetail_LinkToTransaction: "Finance.OutcomingEntry.OutcomingEntryDetail.LinkToTransaction",
    Finance_OutcomingEntry_OutcomingEntryDetail_ViewAllByOutcomingEntry: "Finance.OutcomingEntry.OutcomingEntryDetail.ViewAllByOutcomingEntry",
    Finance_OutcomingEntry_OutcomingEntryDetail_ViewDetail: "Finance.OutcomingEntry.OutcomingEntryDetail.ViewDetail",
    Finance_OutcomingEntry_ViewAll: "Finance.OutcomingEntry.ViewAll",
    Finance_OutcomingEntry_ViewDetail: "Finance.OutcomingEntry.ViewDetail",
    Finance_OutcomingEntry_BankTransaction_GetAllOutcomingEntryByStatusEND: "Finance.OutcomingEntry.BankTransaction.GetAllOutcomingEntryByStatusEND",
    Finance_OutcomingEntry_BankTransaction_SaveMultipleRequest: "Finance.utcomingEntry.BankTransaction.SaveMultipleRequest",

    // supplier
    Finance_OutcomingEntrySupplier: "Finance.OutcomingEntrySupplier",
    Finance_OutcomingEntrySupplier_Create: "Finance.OutcomingEntrySupplier.Create",
    Finance_OutcomingEntrySupplier_RemoveSupplierFromOutcomingEntry: "Finance.OutcomingEntrySupplier.RemoveSupplierFromOutcomingEntry",
    Finance_OutcomingEntrySupplier_Update: "Finance.OutcomingEntrySupplier.Update",
    Finance_RelationInOutEntry: "Finance.RelationInOutEntry",
    Finance_Supplier: "Finance.Supplier",
    Finance_Supplier_Create: "Finance.Supplier.Create",
    Finance_Supplier_Delete: "Finance.Supplier.Delete",
    Finance_Supplier_Get: "Finance.Supplier.Get",
    Finance_Supplier_GetAll: "Finance.Supplier.GetAll",
    Finance_Supplier_GetAllByOutcomingEntry: "Finance.Supplier.GetAllByOutcomingEntry",
    Finance_Supplier_GetAllPaging: "Finance.Supplier.GetAllPaging",
    Finance_Supplier_Update: "Finance.Supplier.Update",
    Finance_RelationInOutEntry_Create: "Finance_RelationInOutEntry.Create",
    Finance_RelationInOutEntry_Delete: "Finance_RelationInOutEntry.Delete",
    Finance_RelationInOutEntry_ViewAll: "Finance_RelationInOutEntry.ViewAll",
    Finance_RelationInOutEntry_ViewInOut: "Finance_RelationInOutEntry.ViewInOut",
}
