export const PERMISSIONS_CONSTANT = {
    Pages_Users: "Pages.Users",
    Pages_Tenants: "Pages.Tenants",
    Pages_Roles: "Pages.Roles",
    Pages_Home: "Pages.Home",

    
    Admin: "true",
    Admin_Client: "true",
    Admin_Client_Create: "true",
    Admin_Client_Delete: "true",
    Admin_Client_Edit: "true",
    Admin_Client_ViewAll: "true",
    CheckList: "CheckList",
    CheckList_CheckListCategory: "CheckList.CheckListCategory",
    CheckList_CheckListCategory_Create: "CheckList.CheckListCategory.Create",
    CheckList_CheckListCategory_Delete: "CheckList.CheckListCategory.Delete",
    CheckList_CheckListCategory_Update: "CheckList.CheckListCategory.Update",
    CheckList_CheckListCategory_ViewAll: "CheckList_CheckListCategory.ViewAll",
    CheckList_CheckListItem: "CheckList.CheckListItem",
    CheckList_CheckListItem_Create: "CheckList.CheckListItem.Create",
    CheckList_CheckListItem_Delete: "CheckList.CheckListItem.Delete",
    CheckList_CheckListItem_Update: "CheckList.CheckListItem.Update",
    CheckList_CheckListItem_ViewAll: "CheckList.CheckListItem.ViewAll",
    CheckList_ProjectChecklist: "true",
    CheckList_ProjectChecklist_AddByProjectType: "true",
    CheckList_ProjectChecklist_Create: "true",
    CheckList_ProjectChecklist_Delete: "true",
    CheckList_ProjectChecklist_ReverseActive: "true",
    DeliveryManagement_PMReport: "DeliveryManagement.PMReport",
    DeliveryManagement_PMReport_CloseReport: "DeliveryManagement.PMReport.CloseReport",
    DeliveryManagement_PMReport_Create: "DeliveryManagement.PMReport.Create",
    DeliveryManagement_PMReport_Delete: "DeliveryManagement.PMReport.Delete",
    DeliveryManagement_PMReport_Update: "DeliveryManagement.PMReport.Update",
    DeliveryManagement_PMReport_ViewAll: "DeliveryManagement.PMReport.ViewAll",
    DeliveryManagement_PMReportProject: "DeliveryManagement.PMReportProject",
    DeliveryManagement_PMReportProject_Create: "DeliveryManagement.PMReportProject.Create",
    DeliveryManagement_PMReportProject_Delete: "DeliveryManagement.PMReportProject.Delete",
    DeliveryManagement_PMReportProject_GetAll: "DeliveryManagement.PMReportProject.GetAll",
    DeliveryManagement_PMReportProject_Update: "DeliveryManagement.PMReportProject.Update",
    DeliveryManagement_ResourceRequest: "DeliveryManagement.ResourceRequest",
    DeliveryManagement_ResourceRequest_AddUserToRequest:"DeliveryManagement.ResourceRequest.AddUserToRequest",
    DeliveryManagement_ResourceRequest_ViewAllByProject: "DeliveryManagement.ResourceRequest.ViewAllByProject",
    DeliveryManagement_ResourceRequest_ApproveUser: "DeliveryManagement.ResourceRequest.ApproveUser",
    DeliveryManagement_ResourceRequest_AvailableResource: "DeliveryManagement.ResourceRequest.AvailableResource",
    DeliveryManagement_ResourceRequest_AvailableResourceFuture: "DeliveryManagement.ResourceRequest.AvailableResourceFuture",
    DeliveryManagement_ResourceRequest_Create: "DeliveryManagement.ResourceRequest.Create",
    DeliveryManagement_ResourceRequest_Delete: "DeliveryManagement.ResourceRequest.Delete",
    DeliveryManagement_ResourceRequest_PlanUser: "DeliveryManagement.ResourceRequest.PlanUser",
    DeliveryManagement_ResourceRequest_RejectUser: "DeliveryManagement.ResourceRequest.RejectUser",
    DeliveryManagement_ResourceRequest_SearchAvailableUserForRequest: "DeliveryManagement.ResourceRequest.SearchAvailableUserForRequest",
    DeliveryManagement_ResourceRequest_Update: "DeliveryManagement.ResourceRequest.Update",
    DeliveryManagement_ResourceRequest_ViewAllResourceRequest: "DeliveryManagement.ResourceRequest.ViewAllResourceRequest",
    DeliveryManagement_ResourceRequest_ViewDetailResourceRequest: "DeliveryManagement.ResourceRequest.ViewDetailResourceRequest",


    
   
    PmManager: "PmManager",
    PmManager_Project: "PmManager.Project",
    PmManager_Project_Create: "PmManager.Project.Create",
    PmManager_Project_Delete: "PmManager.Project.Delete",
    PmManager_Project_Update: "PmManager.Project.Update",
    PmManager_Project_ViewAll: "PmManager.Project.ViewAll",
    PmManager_Project_ViewDetail: "PmManager.Project.ViewDetail",
    PmManager_Project_ViewOnlyMe: "PmManager.Project.ViewOnlyMe",
    PmManager_ProjectUser: "PmManager.ProjectUser",
    PmManager_ProjectUser_Create: "PmManager.ProjectUser.Create",
    PmManager_ProjectUser_Delete: "PmManager.ProjectUser.Delete",
    PmManager_ProjectUser_Update: "PmManager.ProjectUser.Update",
    PmManager_ProjectUser_ViewAllByProject: "PmManager.ProjectUser.ViewAllByProject",
    PmManager_ProjectUserBill: "PmManager.ProjectUserBill",
    PmManager_ProjectUserBill_Create: "PmManager.ProjectUserBill.Create",
    PmManager_ProjectUserBill_Delete: "PmManager.ProjectUserBill.Delete",
    PmManager_ProjectUserBill_GetAllPaging: "PmManager.ProjectUserBill.GetAllPaging",
    PmManager_ProjectUserBill_GetAllbyProject: "PmManager.ProjectUserBill.GetAllbyProject",
    PmManager_ProjectUserBill_Update: "PmManager.ProjectUserBill.Update",
    PmManager_ProjectMilestone:"PmManager.ProjectMilestone",
    PmManager_ProjectMilestone_Create:"PmManager.ProjectMilestone.Create",
    PmManager_ProjectMilestone_Delete:"PmManager.ProjectMilestone.Delete",
    PmManager_ProjectMilestone_Update:"PmManager.ProjectMilestone.Update",
    PmManager_ProjectMilestone_ViewAll:"PmManager.ProjectMilestone.ViewAll",

    PmManager_Timesheet_GetAllProjectTimesheetByTimesheet: "true",
    PmManager_Timesheet_ViewOnlyActiveProject: "true",
    PmManager_Timesheet_ViewOnlyMe: "true",
    PmManager_TimesheetProject: "true",
    PmManager_TimesheetProject_Create: "true",
    PmManager_TimesheetProject_Delete: "true",
    PmManager_TimesheetProject_GetAllByProject: "true",
    PmManager_TimesheetProject_GetAllRemainProjectInTimesheet: "true",
    PmManager_TimesheetProject_Update: "true",
    PmManager_TimesheetProject_UploadFileTimesheetProject: "true",
    SaoDo: "SaoDo",
    SaoDo_AuditResultPeople: "SaoDo.AuditResultPeople",
    SaoDo_AuditResultPeople_Create: "SaoDo.AuditResultPeople.Create",
    SaoDo_AuditResultPeople_Delete: "SaoDo.AuditResultPeople.Deletee",
    SaoDo_AuditResultPeople_Update: "SaoDo.AuditResultPeople.Update",
    SaoDo_AuditSession: "SaoDo.AuditSession",
    SaoDo_AuditSession_AddAuditResult: "SaoDo.AuditSession.AddAuditResult",
    SaoDo_AuditSession_Create: "SaoDo.AuditSession.Create",
    SaoDo_AuditSession_Delete: "SaoDo.AuditSession.Delete",
    SaoDo_AuditSession_Update: "SaoDo.AuditSession.Update", 
    SaoDo_AuditSession_View: "SaoDo.AuditSession.View",
    SaoDo_AuditSession_ViewAll: "SaoDo.AuditSession.ViewAll",
    Timesheet: "Timesheet",
    Timesheet_Timesheet: "Timesheet.Timesheet",
    Timesheet_Timesheet_Create: "Timesheet.Timesheet.Create",
    Timesheet_Timesheet_Delete: "Timesheet.Timesheet.Delete",
    Timesheet_Timesheet_DoneTimesheetById: "Timesheet.Timesheet.DoneTimesheetById",
    Timesheet_Timesheet_Get: "Timesheet.Timesheet.Get",
    Timesheet_Timesheet_Update: "Timesheet.Timesheet.Update",
    Timesheet_Timesheet_ViewAll: "Timesheet.Timesheet.ViewAll",
    
    
}
